version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
    - method: setuptools
      path: .

sphinx:
  builder: html
  fail_on_warning: false
  configuration: docs/source/conf.py
