version: '3.10'

services:
  biomania-frontend:
    image: chatbotuibiomania/biomania-frontend:v1.1.9
    environment:
      - BACKEND_URL=http://biomania-backend:5000
    ports:
      - "3000:3000"
    restart: always
    networks:
      - mynetwork


  biomania-backend:
    image: chatbotuibiomania/biomania-backend:v1.1.9
    environment:
      - OPENAI_API_KEY=""
    ports:
      - "5000:5000"
    restart: always
    networks:
      - mynetwork
    runtime: nvidia

networks:
  mynetwork:
